arb-dir: lib/l10n
template-arb-file: intl_id.arb
synthetic-package: false
output-localization-file: app_localizations.dart
output-class: AppLocalizations
# Or, specifically provide an output path:
output-dir: lib/src/generated/i18n